import { Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    title: "GitFreak";

    width: 1000px;
    height: 700px;

    in property <string> repository-path: "";
    in property <string> status-text: "No repository opened.";

    callback open-repository();

    VerticalLayout {
        alignment: center;
        spacing: 20px;

        Text {
            text: "GitFreak";
            font-size: 36px;
            horizontal-alignment: center;
        }

        Text {
            text: "Your Git, your way.";
            font-size: 18px;
            horizontal-alignment: center;
        }

        Button {
            text: "Open Repository";

            clicked => {
                root.open-repository();
            }
        }

        Text {
            text: status-text;
            horizontal-alignment: center;
        }

        Text {
            text: repository-path;
            horizontal-alignment: center;
        }
    }
}